<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLsc3Uxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLsc3Uxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLsc3Uxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLsc3Uxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLsc3Uxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lsc3Uxx',
    'container.build_id' => 'ce1ca5e5',
    'container.build_time' => 1711885802,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLsc3Uxx');
